### ISSUE TITLE
Scala Days Berlin v2

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scaladex#60]
* [x] ui for oauth2 login (#12)
* [x] collaborator can edit information (#49)
* [x] improve search relevance (#56)
* [x] new projects, new releases in front page (#54)
* [x] select artifact & release + target in project page (#58)
* [x] keywords in project page (#21)
* [x] + license info (#22)
* [x] contributor wanted (#25)
* [x] cookie warning (#3)
* [x] repo statistics from GitHub visible (#115)
* [x] restore autocomplete/dropdown bar (#122)
