### ISSUE TITLE
Deploy develop branch to production - Remaning tasks 

### ISSUE THREAD

**Issue by mlachkar** [scalacenter/scaladex#746]
We have been working actively on scaladex since August and the goal is to change some architecture design decisions that were blocking us from fixing some features. The work is still in progress but the goal of this ticket is to list the remaining tickets that are necessary before pushing to prod. 

- [x] github synchronization #743 
- [x] Fixe renamed projects and make sure that the claims mechanism is still working #744  
- [ ] Test the publish api to make sure that it's not broken. Right now we don't have any tests for this part. 

Nice to have 
- [ ] improve badge support and offer more badges  #719 
- [ ] New design to show the project to contribute to, project trends
- [x] fix the button "show my projects" #745

**Comment by adpi2** [comment]
Also I would like to add:

- [ ] Rename package `ch.epfl.scala.index` to `scaladex`
- [ ] Review the naming uniformity

**Comment by mlachkar** [comment]
scaladex has been deployed to production
