### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scaladex#81]
Really excited to see this take off 😄 Here are a few things I noticed.
- [x] I would be really nice to see immediately what Scala versions libraries support (e.g., 2.10/2.11/..., Scala.js)
  - targets in [project](https://github.com/scalacenter/scaladex/blob/master/model/src/main/scala/ch.epfl.scala.index.model/Project.scala#L45) (ex: scala_2.11, scala.js_0.6)
  - [seach result html templating](https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/result.scala.html#L42) 
**moved to #288**
- [x] Dependents should not include libraries from the same repo, for example https://index.scala-lang.org/typelevel/cats-free has https://index.scala-lang.org/typelevel/cats has a dependent
  - [html templating](https://github.com/scalacenter/scaladex/blob/master/template/src/main/twirl/ch.epfl.scala.index.views/project/dependents.scala.html)
  - [release model](https://github.com/scalacenter/scaladex/blob/master/model/src/main/scala/ch.epfl.scala.index.model/Release.scala#L37)
  - same repo == same [Project.Reference](https://github.com/scalacenter/scaladex/blob/master/model/src/main/scala/ch.epfl.scala.index.model/Release.scala#L215)
- [x] Dependencies includes sbt plugins and test dedendencies. For example for [scalafmt-core](https://index.scala-lang.org/olafurpg/scalafmt-core), it lists 6 dependencies out of which only scalameta and sourcecode are actual dependencies to the published library.
- [x] The CSS is slightly broken in Chrome (fixed in #75)

<img width="390" alt="screen shot 2016-06-16 at 07 37 15" src="https://cloud.githubusercontent.com/assets/1408093/16116374/c8132742-33cc-11e6-95bc-c712bf6734b3.png">
- [X] The recent releases list doesn't contain links to the projects, only their names (fixed in #74)
- [x] The recent releases seem to have duplicates, for example the top three libraries now are
  - kaliber - play-s3 6.0.0
  - kaliber - play-s3 8.0.0
  - kaliber - play-s3 7.0.2
- [X] The version number defaults to the latest release even if it's a RC. I think it would be cool to show the latest stable release as well. (#78)
- [X] The search  bar is missing from the search results page: https://index.scala-lang.org/search?q=scala-js&page=1&sort=relevant (fixed in 1c8fc3da924b59b2328509f5706d35db3a3dcdaf)
- [x] The search needs some fine tuning. Some ideas:
  - most relevant should be the default ordering criteria.
  - most relevant needs to improve, for example scala.js is the 8th result when searching for "scala-js" and scalatags is result number 2 for the query "scalatags" https://index.scala-lang.org/search?q=scalatags&page=1&sort=relevant
  - searching "fmt" yields 5 libraries that don't have fmt in their name, and scalafmt did not show up
- [X] SBT/Gradle/Maven coordinates show up twice (duplicates #66), for example [here](https://index.scala-lang.org/lihaoyi/scalatags), see

<img width="96" alt="scaladex_-_scalatags" src="https://cloud.githubusercontent.com/assets/1408093/16117050/6723d41e-33d0-11e6-8aa1-49806ccb7190.png">
- [x] Projects with the same github url have different scaladex pages. For example https://index.scala-lang.org/apache/spark-hive and https://index.scala-lang.org/apache/spark-core
- [x] Dependents should list libraries that depend on that artifact, regardless of what version number those libraries use. For example https://index.scala-lang.org/typelevel/cats/0.5.0 has 3 dependents and https://index.scala-lang.org/typelevel/cats/0.6.0 has 5

**Comment by MasseGuillaume** [comment]
> Projects with the same github url have different scaladex pages. For example https://index.scala-lang.org/apache/spark-hive and https://index.scala-lang.org/apache/spark-core

This is on purpose. You dont like this organization? I could suggest something like: https://index.scala-lang.org/apache/spark/core. It does not always work however.

**Comment by MasseGuillaume** [comment]
> Dependents should not include libraries from the same repo

I think we should show:

* Dependencies
* Dependent
* Project-Dependencies (Dependencies and Dependent for the same project).

Project-Dependencies would help for navigation.

I Updated Olaf comment to point out relevant source code.
