### ISSUE TITLE
Add a mechanism to update `UserState`

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scaladex#977]
### Motivation

Currently the user state is loaded once at first login but then it is never updated.

To solve this issue I see two possible directions:
1. Update each time we receive a `userId` from the client. The response should not wait for the userState update because the update can be slow (~10 seconds).
2. Add a scheduled job that update all user states every once in while

I would suggest solution 2 because it is easier to monitor: we can easily track the number of updated user states and catch failures.

### Identified Obstacles

If the user revokes its token, the GET requests in `GithubClient` will fail. We should catch the failure and identify that the token is no longer valid and remove the corresponding user session from the database. It will automatically log the user out.

### Implementation Guideline

1. In `SchedulerService` create a new scheduler
2. The scheduler should load all `UserState` from the database
3. For each user it should use its token to create a `GithubClient`
4. It uses the `GithubClient` to load the new state
5. Update the state in the database

### Expectations

1. The scheduled job should run once in while and not consume too much resources (avoid too much parallelization)
2. The failure from `GithubClient` should distinguish between revoked token or some other failure.

### Tasks
- [ ] Add a database query that reads all user states from the database.
- [ ] Add scheduled job that uses the query above (ignore the failures as a first step).
- [ ] Identify revoked tokens and remove corresponding user states from the database.

**Comment by jyoo980** [comment]
This sounds like a nice continuation of my work in #947, happy to take this on 🙂

**Comment by adpi2** [comment]
Perfect, thanks @jyoo980
