### ISSUE TITLE
Add /artifacts endpoint in the programmatic API

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scaladex#982]
### Motivation

The Scaladex API could be used to list the available artifacts for a particular Scala version and/or platform.

We can do so by adding a new endpoint:
```
/api/artifacts?platform=<...>&language=<...>
```
Where `platform` and `language` are optional parameters.

Examples:
- all artifacts: `/api/artifacts`
- all Scala 2.13 artifacts: `/api/artifacts?language=2.13`
- all Scala.js 1.x artifacts: `/api/artifacts?platform=sjs1`
- all Scala.js 1.x artifacts on Scala 3: `/api/artifacts?platform=sjs1&language=3`

It returns a list of `groupid` and `artifact-id` in json:
```json
{
  "items": [
    {
      "groupid": "ch.epfl.scala",
      "artifactid": "scala-debug-adapter_2.13"
    },
   {
      "groupid": "ch.epfl.scala",
      "artifactid": "scalafix_2.13"
   }
  ]
}
```

### Identified Obstacles

We will probably implement paging as a second step. But can it work without a paging?

### Implementation Guideline

1. Add  a new `ArtifactEndpoints` in `modules/core/shared/src/main/scala/scaladex/core/api` and define `ArtifactParams` and `ArtifactResponse`. We use `endpoints4s` to document the API.
2. Add a new method `getAllArtifacts(language: Option[Language], platform: Option[Platform])` in `WebDatabase` and implement it in the `SqlDatabase` class.
3. Add an `ArtifactApi` class in `server/src/main/scala/scaladex/server/route/api/` to define the akka-http route that implement the endoint in `ArtifactEndpoint` using the new method in the database. Configure this route in `Server`.
4. Also add the `ArtifactEndpoint` endpoint in `DocumentationRoutes` for documentation

### Expectations

1. The `getAllArtifacts` method and SQL requests should be tested in `SqlDatabaseTests` and `ArtifactTableTests`
2. The `ArtifactApi` route should be tested in a new `ArtifactApiTests` using the `ControllerBaseSuite` that contains a mock of the database.
3. The new endpoint should be deployed and it should appear in the documentation endpoint `/api/open-api.json` 

### Tasks

 - [x] Add  a new `ArtifactEndpoints` in `modules/core/shared/src/main/scala/scaladex/core/api` and define `ArtifactParams` and `ArtifactResponse`. We use `endpoints4s` to document the API.
 - [x] Add a new method `getAllArtifacts(language: Option[Language], platform: Option[Platform])` in `WebDatabase` and implement it in the `SqlDatabase` class.
   - [x] The methods above should be tested
- [x] Add an `ArtifactApi` class in `server/src/main/scala/scaladex/server/route/api/` to define the akka-http route that implement the endoint in `ArtifactEndpoint` using the new method in the database. Configure this route in `Server`.
- [x] Also add the `ArtifactEndpoint` endpoint in `DocumentationRoutes` for documentation

**Comment by jyoo980** [comment]
I've implemented some of the tasks in #992
