### ISSUE TITLE
Add endpoint `api/artifacts/<group_id>/<artifact_id>` to obtain metadata for a given artifact

### ISSUE THREAD

**Issue by jyoo980** [scalacenter/scaladex#998]
## Summary

Currently, the `api/artifacts` endpoint returns a list of all artifacts with the response below:

```
{
  "items": [
    {
      "groupid": "ch.epfl.scala",
      "artifactid": "scala-debug-adapter_2.13"
    },
    {
       "groupid": "ch.epfl.scala",
       "artifactid": "scalafix_2.13"
    }
  ]
}
```

We now want to add an endpoint that enables clients to get the [semantic version](https://github.com/scalacenter/scaladex/blob/main/modules/core/shared/src/main/scala/scaladex/core/model/Artifact.scala#L22) of an artifact given its `groupId` and `artifactId`. 

The endpoint should have the form:

```
api/artifacts/<group_id>/<artifact_id>
```

It should respond with a value of type `Page[ArtifactMetadata]`, where the metadata type has the following information

```
// ArtifactMetadata object for cats-core
{
  "version": "2.7.0",
  "project_reference": "typelevel/cats",
  "release_date": "Nov 28, 2021",
  "language": "Scala 2.13",
  "platform": "JVM"
}
```

## Tasks

- [x] Add a method in `WebDatabase` to select an artifact, given a `groupId` and an `artifactId`
  - [x] This method should be tested in `SqlDatabaseTests` and `ArtifactTableTests`
- [x] Create an endpoint in `ArtifactEndpoints.scala` for `api/artifacts/<group_id>/<artifact_id>`
  - [x] This method should be tested in `ArtifactApiTests.scala`

## Other Details
This work is the result of [this discussion](https://github.com/scalacenter/scaladex/discussions/997).

**Comment by adpi2** [comment]
Thanks for opening this issue!

On second thoughts, the response could contain more than just the version. It could also contains some of the information we have the current [`Artifact`](https://github.com/scalacenter/scaladex/blob/d59165e8b31a19a9351df4bccdce83bb8ebb7245/modules/core/shared/src/main/scala/scaladex/core/model/Artifact.scala#L15-L32) in our model. A good starting point would be:

```
version: String
project_reference: Option[String] // example: "typelevel/cats"
release_date: String
language: String
platform: String
```

We can add more later.

**Comment by jyoo980** [comment]
Works for me, I'll update the ticket later!

**Comment by jyoo980** [comment]
@adpi2 I'm trying to think about how to create a query for `ArtifactTable.scala` that would select an artifact given an `Artifact.GroupId` and `Artifact.ArtifactId`:

```scala
  val selectArtifactByGroupIdAndArtifactId: Query[(Artifact.GroupId, Artifact.ArtifactId), Artifact] =
    selectRequest(table, Seq("*"), Seq("group_id", "artifact_name", "version"))
```

Would this make sense?

**Comment by adpi2** [comment]
A single artifact is identified by a Maven reference which is composed of the group id, the artifact id and a the version (also called revision sometimes).

An example of that is `org.typelevel:cats-core_2.13:2.7.0` (see [here](https://repo1.maven.org/maven2/org/typelevel/cats-core_2.13/2.7.0/) in maven central). `org.typelevel` is the group id, `cats-core_2.13` is the artifact id and `2.7.0` is the version.

Notice that the artifact id is made of two parts, the artifact name (`cats-core`) and the binary version `2.13`. That's a trick that we use in the Scala ecosystem to find the artifact that is compatible on a particular Scala version or platform. The binary version can contain one or two parts too: the language version (`_2.13`) and the platform (`_sjs1` for Scala.js 1.x, `native0.4` for Scala Native 0.4).

We have some redundancy in our artifacts table because we have the `artifact_id` column but also we have the `artifact_name`, `language_version` and `platform` columns. So there are two possible queries.

```
val selectArtifactByGroupIdAndArtifactId: Query[(Artifact.GroupId, Artifact.ArtifactId), Artifact] =
    selectRequest(table, fields, Seq("group_id", "artifact_id"))

val selectArtifactByGroupIdAndArtifactId: Query[(Artifact.GroupId, Artifact.AritfactName, Language, Platform), Artifact] =
    selectRequest(table, fields, Seq("group_id", "artifact_name", "language_version", "platform"))
```

I recommend using the first one: it is simpler and more optimized because "group_id" and "artifact_id" are parts of the primary key.

**Comment by jyoo980** [comment]
Great, that makes sense.

There's a long weekend coming up so I'm excited to work on this 😁

**Comment by adpi2** [comment]
That's great to hear. I am really amazed by all the work you do.

I have some more issues to open and hopefully I will find the time to do it sooner rather than later.

**Comment by jyoo980** [comment]
Hmm... now I'm curious whether the database call should return a single artifact or a list of artifacts. Isn't there a possibility of there being more than one artifact with the same `groupId` and `artifactId`?

For example, in here https://github.com/scalacenter/scaladex/blob/70e4732e1ef46e2c0cc7370a1accca657bbd7691/modules/core/shared/src/test/scala/scaladex/core/test/Values.scala#L169-L171

We see that these three artifacts would have the same `groupId` (`org.typelevel`), and `artifactId` (`cats-core_3`). But maybe I am misunderstanding something.

**Comment by adpi2** [comment]
> So the ultimate response should look something like
```json
{
  "pagination": { ... },
  "items": [
      {
        "version": "2.7.0",
        "project_reference": "typelevel/cats",
        "release_date": "Nov 28, 2021", // ...
        "language": "Scala 2.13",
        "platform": "JVM"
      },
      {
        "version": "2.6.1",
        "project_reference": "typelevel/cats",
        "release_date": "Nov 28, 2021", // just using a placeholder date for example
        "language": "Scala 2.13",
        "platform": "JVM"
    }, ...
  ]
}
```

Yes absolutely.
